version: "3"

services:
  #  backend:
  #    build:
  #      context: .
  #      target: development
  #    env_file:
  #      - .env
  #    depends_on:
  #      - postgres
  #    ports:
  #      - '3000:3000'
  #    command:
  #      - npm run migration:run
  #      - npm run migrate:seed
  #     - npm run start:dev

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
